spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    banner-mode: 'OFF'
  jackson:
    serialization:
      write-dates-as-timestamps: false
    pathmatch:
      matching-strategy: ant_path_matcher
      
          

message:
  validators:
    sendToKafka: "uma ou mais mensagens não atendem ao requisito de negócio"
